// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9s969TKo7DxUL-0k36whnPSTLEMmvom0',
    appId: '1:573744469754:web:ad8f2bdaf87c5bc0c61b43',
    messagingSenderId: '573744469754',
    projectId: 'manassa-cb59f',
    authDomain: 'manassa-cb59f.firebaseapp.com',
    databaseURL: 'https://manassa-cb59f-default-rtdb.firebaseio.com',
    storageBucket: 'manassa-cb59f.appspot.com',
    measurementId: 'G-D3TDG57627',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJEn4WrneG-zC3a2BvNiumwwYQQG8-5o',
    appId: '1:573744469754:android:566db1a6bf7f8bf3c61b43',
    messagingSenderId: '573744469754',
    projectId: 'manassa-cb59f',
    databaseURL: 'https://manassa-cb59f-default-rtdb.firebaseio.com',
    storageBucket: 'manassa-cb59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN0G6qbk16D4zEg_RYy3Z5m3dpMAcMIi8',
    appId: '1:573744469754:ios:efac3be36167f5aec61b43',
    messagingSenderId: '573744469754',
    projectId: 'manassa-cb59f',
    databaseURL: 'https://manassa-cb59f-default-rtdb.firebaseio.com',
    storageBucket: 'manassa-cb59f.appspot.com',
    iosBundleId: 'com.manassa.manassa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN0G6qbk16D4zEg_RYy3Z5m3dpMAcMIi8',
    appId: '1:573744469754:ios:efac3be36167f5aec61b43',
    messagingSenderId: '573744469754',
    projectId: 'manassa-cb59f',
    databaseURL: 'https://manassa-cb59f-default-rtdb.firebaseio.com',
    storageBucket: 'manassa-cb59f.appspot.com',
    iosBundleId: 'com.manassa.manassa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9s969TKo7DxUL-0k36whnPSTLEMmvom0',
    appId: '1:573744469754:web:d346c6c01a9a605bc61b43',
    messagingSenderId: '573744469754',
    projectId: 'manassa-cb59f',
    authDomain: 'manassa-cb59f.firebaseapp.com',
    databaseURL: 'https://manassa-cb59f-default-rtdb.firebaseio.com',
    storageBucket: 'manassa-cb59f.appspot.com',
    measurementId: 'G-7VXTHDN9YS',
  );
}
